<?php

namespace PixelApp\Database\Factories\SystemConfigurationFactories;

use PixelApp\Database\Factories\PixelBaseFactory as Factory;

class PermissionsTableSeederFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'name' =>
            $this->faker->unique()->randomElement(
                [
                    "read_personal-sector-dashboard",
                    "read_personal-sector-expenses",
                    "create_personal-sector-expenses",
                    "edit_personal-sector-expenses",
                    "delete_personal-sector-expenses",
                    "read_personal-sector-custody",
                    "create_personal-sector-custody",
                    "edit_personal-sector-custody",
                    "delete_personal-sector-custody",
                    "read_sc-dropdown-lists",
                    "create_sc-dropdown-lists",
                    "edit_sc-dropdown-lists",
                    "delete_sc-dropdown-lists",
                    "read_sc-roles-and-permissions",
                    "create_sc-roles-and-permissions",
                    "edit_sc-roles-and-permissions",
                    "delete_sc-roles-and-permissions",
                    "read_emm-signup-list",
                    "create_emm-signup-list",
                    "edit_emm-signup-list",
                    "delete_emm-signup-list",
                    "approve_emm-signup-list",
                    "read_emm-employees-list",
                    "create_emm-employees-list",
                    "edit_emm-employees-list",
                    "delete_emm-employees-list",
                    "read_cmm-clients-list",
                    "create_cmm-clients-list",
                    "edit_cmm-clients-list",
                    "delete_cmm-clients-list",
                    "read_cmm-clients-quotations",
                    "create_cmm-clients-quotations",
                    "edit_cmm-clients-quotations",
                    "delete_cmm-clients-quotations",
                    "approve_cmm-clients-quotations",
                    "read_cmm-clients-orders",
                    "create_cmm-clients-orders",
                    "edit_cmm-clients-orders",
                    "delete_cmm-clients-orders",
                    "read_vmm-vendors-list",
                    "create_vmm-vendors-list",
                    "edit_vmm-vendors-list",
                    "delete_vmm-vendors-list",
                    "read_vmm-vendors-orders",
                    "create_vmm-vendors-orders",
                    "edit_vmm-vendors-orders",
                    "delete_vmm-vendors-orders",
                    "read_sfm-finances-summary",
                    "create_sfm-finances-summary",
                    "edit_sfm-finances-summary",
                    "delete_sfm-finances-summary",
                    "read_sfm-purchase-invoices",
                    "create_sfm-purchase-invoices",
                    "edit_sfm-purchase-invoices",
                    "delete_sfm-purchase-invoices",
                    "approve_sfm-purchase-invoices",
                    "read_sfm-sales-invoices",
                    "create_sfm-sales-invoices",
                    "edit_sfm-sales-invoices",
                    "delete_sfm-sales-invoices",
                    "approve_sfm-sales-invoices",
                    "read_sfm-assets-list",
                    "create_sfm-assets-list",
                    "edit_sfm-assets-list",
                    "delete_sfm-assets-list",
                    "read_sfm-taxes-and-insurances",
                    "create_sfm-taxes-and-insurances",
                    "edit_sfm-taxes-and-insurances",
                    "delete_sfm-taxes-and-insurances",
                    "create_com-signup-list",
                    "approve_com-signup-list",
                    "reject_com-signup-list",
                    "edit_com-signup-list",
                    "delete_com-signup-list",
                    "read_com-signup-list",
                    "create_com-companies-list",
                    "edit_com-companies-list",
                    "delete_com-companies-list",
                    "read_com-companies-list",

                    "create_com-packages-management",
                    "edit_com-packages-management",
                    "delete_com-packages-management",
                    "read_com-packages-management",

                    "create_com-companies-management",
                    "edit_com-companies-management",
                    "delete_com-companies-management",
                    "read_com-companies-management",

                    "create-com-packages-management-packages-tab",
                    "edit-com-packages-management-packages-tab",
                    "delete-com-packages-management-packages-tab",
                    "read-com-packages-management-packages-tab",

                    "create_com-packages-management-offers-tab",
                    "edit_com-packages-management-offers-tab",
                    "delete_com-packages-management-offers-tab",
                    "read_com-packages-management-offers-tab",

                    "create_com-packages-management-packages-price-tab",
                    "edit_com-packages-management-packages-price-tab",
                    "delete_com-packages-management-packages-price-tab",
                    "read_com-packages-management-packages-price-tab",

                    //////// aduit
                    "read_ga-process-saftey-audit",

                    "read_ga-process-saftey-audit-reports-tab",
                    "create_ga-process-saftey-audit-reports-tab",
                    "edit_ga-process-saftey-audit-reports-tab",
                    "delete_ga-process-saftey-audit-reports-tab",

                    "read_ga-process-saftey-audit-questions-tab",
                    "create_ga-process-saftey-audit-questions-tab",
                    "edit_ga-process-saftey-audit-questions-tab",
                    "delete_ga-process-saftey-audit-questions-tab",

                    "read_ga-chemical-management-audit",

                    "read_ga-chemical-management-audit-reports-tab",
                    "create_ga-chemical-management-audit-reports-tab",
                    "edit_ga-chemical-management-audit-reports-tab",
                    "delete_ga-chemical-management-audit-reports-tab",

                    "read_ga-chemical-management-audit-questions-tab",
                    "create_ga-chemical-management-audit-questions-tab",
                    "edit_ga-chemical-management-audit-questions-tab",
                    "delete_ga-chemical-management-audit-questions-tab",

                    "read_ga-driving-safety-audit",

                    "read_ga-driving-safety-audit-reports-tab",
                    "create_ga-driving-safety-audit-reports-tab",
                    "edit_ga-driving-safety-audit-reports-tab",
                    "delete_ga-driving-safety-audit-reports-tab",

                    "read_ga-driving-safety-audit-questions-tab",
                    "create_ga-driving-safety-audit-questions-tab",
                    "edit_ga-driving-safety-audit-questions-tab",
                    "delete_ga-driving-safety-audit-questions-tab",

                    "read_ga-emergency-response",

                    "read_ga-emergency-response-reports-tab",
                    "create_ga-emergency-response-reports-tab",
                    "edit_ga-emergency-response-reports-tab",
                    "delete_ga-emergency-response-reports-tab",

                    "read_ga-emergency-response-questions-tab",
                    "create_ga-emergency-response-questions-tab",
                    "edit_ga-emergency-response-questions-tab",
                    "delete_ga-emergency-response-questions-tab",

                    "read_ga-fatiuge-audit",

                    "read_ga-fatiuge-audit-reports-tab",
                    "create_ga-fatiuge-audit-reports-tab",
                    "edit_ga-fatiuge-audit-reports-tab",
                    "delete_ga-fatiuge-audit-reports-tab",

                    "read_ga-fatiuge-audit-questions-tab",
                    "create_ga-fatiuge-audit-questions-tab",
                    "edit_ga-fatiuge-audit-questions-tab",
                    "delete_ga-fatiuge-audit-questions-tab",

                    "read_ga-food-safety-audit",
                    "read_ga-food-safety-audit-reports-tab",
                    "create_ga-food-safety-audit-reports-tab",
                    "edit_ga-food-safety-audit-reports-tab",
                    "delete_ga-food-safety-audit-reports-tab",
                    "read_ga-food-safety-audit-questions-tab",
                    "create_ga-food-safety-audit-questions-tab",
                    "edit_ga-food-safety-audit-questions-tab",
                    "delete_ga-food-safety-audit-questions-tab",

                    "read_ga-hse-legal-requiremens-audit",
                    "read_ga-hse-legal-requiremens-audit-reports-tab",
                    "create_ga-hse-legal-requiremens-audit-reports-tab",
                    "edit_ga-hse-legal-requiremens-audit-reports-tab",
                    "delete_ga-hse-legal-requiremens-audit-reports-tab",
                    "read_ga-hse-legal-requiremens-audit-questions-tab",
                    "create_ga-hse-legal-requiremens-audit-questions-tab",
                    "edit_ga-hse-legal-requiremens-audit-questions-tab",
                    "delete_ga-hse-legal-requiremens-audit-questions-tab",

                    "read_ga-medical-emergency-response-plan-audit",
                    "read_ga-medical-emergency-response-plan-audit-reports-tab",
                    "create_ga-medical-emergency-response-plan-audit-reports-tab",
                    "edit_ga-medical-emergency-response-plan-audit-reports-tab",
                    "delete_ga-medical-emergency-response-plan-audit-reports-tab",
                    "read_ga-medical-emergency-response-plan-audit-questions-tab",
                    "create_ga-medical-emergency-response-plan-audit-questions-tab",
                    "edit_ga-medical-emergency-response-plan-audit-questions-tab",
                    "delete_ga-medical-emergency-response-plan-audit-questions-tab",

                    "read_ga-potable-water-audit",
                    "read_ga-potable-water-audit-reports-tab",
                    "create_ga-potable-water-audit-reports-tab",
                    "edit_ga-potable-water-audit-reports-tab",
                    "delete_ga-potable-water-audit-reports-tab",
                    "read_ga-potable-water-audit-questions-tab",
                    "create_ga-potable-water-audit-questions-tab",
                    "edit_ga-potable-water-audit-questions-tab",
                    "delete_ga-potable-water-audit-questions-tab",

                    "read_ga-procedures-management-system-audit",
                    "read_ga-procedures-management-system-audit-reports-tab",
                    "create_ga-procedures-management-system-audit-reports-tab",
                    "edit_ga-procedures-management-system-audit-reports-tab",
                    "delete_ga-procedures-management-system-audit-reports-tab",
                    "read_ga-procedures-management-system-audit-questions-tab",
                    "create_ga-procedures-management-system-audit-questions-tab",
                    "edit_ga-procedures-management-system-audit-questions-tab",
                    "delete_ga-procedures-management-system-audit-questions-tab",

                    "read_ga-safety-critical-equipment-audit",
                    "read_ga-safety-critical-equipment-audit-reports-tab",
                    "create_ga-safety-critical-equipment-audit-reports-tab",
                    "edit_ga-safety-critical-equipment-audit-reports-tab",
                    "delete_ga-safety-critical-equipment-audit-reports-tab",
                    "read_ga-safety-critical-equipment-audit-questions-tab",
                    "create_ga-safety-critical-equipment-audit-questions-tab",
                    "edit_ga-safety-critical-equipment-audit-questions-tab",
                    "delete_ga-safety-critical-equipment-audit-questions-tab",

                    "read_ga-unpermitted-persistent-releases-audit",
                    "read_ga-unpermitted-persistent-releases-audit-reports-tab",
                    "create_ga-unpermitted-persistent-releases-audit-reports-tab",
                    "edit_ga-unpermitted-persistent-releases-audit-reports-tab",
                    "delete_ga-unpermitted-persistent-releases-audit-reports-tab",
                    "read_ga-unpermitted-persistent-releases-audit-questions-tab",
                    "create_ga-unpermitted-persistent-releases-audit-questions-tab",
                    "edit_ga-unpermitted-persistent-releases-audit-questions-tab",
                    "delete_ga-unpermitted-persistent-releases-audit-questions-tab",

                    "read_fm-maintenance-action",
                    "create_fm-maintenance-action",
                    "edit_fm-maintenance-action",
                    "delete_fm-maintenance-action",

                    "read_fm-list",
                    "create_fm-list",
                    "edit_fm-list",
                    "delete_fm-list",

                    "read_fsl-gas",
                    "create_fsl-gas",
                    "edit_fsl-gas",
                    "delete_fsl-gas",

                    "read_fsl-control-panel",
                    "create_fsl-control-panel",
                    "edit_fsl-control-panel",
                    "delete_fsl-control-panel",

                    "read_fsl-water",
                    "create_fsl-water",
                    "edit_fsl-water",
                    "delete_fsl-water",

                    "read_fsl-foam",
                    "create_fsl-foam",
                    "edit_fsl-foam",
                    "delete_fsl-foam",

                    "read_fsl-fire-network",

                    "read_fsl-fire-network-pipeline-tab",
                    "edit_fsl-fire-network-pipeline-tab",
                    "delete_fsl-fire-network-pipeline-tab",
                    "create_fsl-fire-network-pipeline-tab",
                    "read_fsl-fire-network-network-tab",
                    "edit_fsl-fire-network-network-tab",
                    "create_fsl-fire-network-network-tab",
                    "delete_fsl-fire-network-network-tab",

                    "read_fsl-hosereels",
                    "create_fsl-hosereels",
                    "edit_fsl-hosereels",
                    "delete_fsl-hosereels",
                    "read_fsl-fire-extinguishers",
                    "create_fsl-fire-extinguishers",
                    "edit_fsl-fire-extinguishers",
                    "delete_fsl-fire-extinguishers",
                    "read_fsl-fire-pumps",
                    "create_fsl-fire-pumps",
                    "edit_fsl-fire-pumps",
                    "delete_fsl-fire-pumps",
                    "read_fsl-fire-hydrant",
                    "create_fsl-fire-hydrant",
                    "edit_fsl-fire-hydrant",
                    "delete_fsl-fire-hydrant",
                    "read_com-signup-list",
                    "create_com-signup-list",
                    "edit_com-signup-list",
                    "delete_com-signup-list",
                    "read_com-companies-list",
                    "create_com-companies-list",
                    "edit_com-companies-list",
                    "delete_com-companies-list",
                    "approve_com-signup-list",
                    "reject_com-signup-list",
                    "read_com-companies-management",
                    "create_com-companies-management",
                    "edit_com-companies-management",
                    "delete_com-companies-management",
                    "read_ma-general-visual-tour",
                    "create_ma-general-visual-tour",
                    "edit_ma-general-visual-tour",
                    "delete_ma-general-visual-tour",
                    "read_ma-preventive-maintenance",
                    "create_ma-preventive-maintenance",
                    "edit_ma-preventive-maintenance",
                    "delete_ma-preventive-maintenance",
                    "read_ma-reactive-maintenance",
                    "create_ma-reactive-maintenance",
                    "edit_ma-reactive-maintenance",
                    "delete_ma-reactive-maintenance",
                    "read_ma-repair",
                    "create_ma-repair",
                    "edit_ma-repair",
                    "delete_ma-repair",
                    "read_ma-replace",
                    "create_ma-replace",
                    "edit_ma-replace",
                    "delete_ma-replace",
                    "read_ma-isolate",
                    "create_ma-isolate",
                    "edit_ma-isolate",
                    "delete_ma-isolate",
                ]
            ),

            'guard_name' =>
            $this->faker->randomElement(
                [
                    'api'
                ]
            ),

            'created_at' => $this->faker->dateTimeBetween('-3 year', '+3 year'),
            'updated_at' => $this->faker->dateTimeBetween('-3 year', '+3 year'),


        ];

    }
}
