<?php

namespace PixelApp\Services\SystemConfigurationServices\DropdownLists\DepartmentsOperations;

use AuthorizationManagement\PolicyManagement\Policies\BasePolicy;
use Exception;
use PixelApp\Models\PixelModelManager;
use PixelApp\Models\SystemConfigurationModels\Department;
use PixelApp\Services\CoreServices\BulkDestroyService;

class DepartmentDeletingService extends BulkDestroyService
{
    protected function getModelDeletingFailingErrorMessage(): string
    {
        return 'Failed to delete the record.';
    }
    protected function getModelDeletingSuccessMessage(): string
    {
        return "The record has been deleted successfully.";
    }

    protected function AuthorizeByPolicy(): bool
    {
        return BasePolicy::check('delete', $this->getModelClass());
    }

    protected function getModelClass(): string
    {
        return PixelModelManager::getModelForModelBaseType(Department::class);
    }

     function doSomeActionsForCollectionBeforeDelete($modelsToDelete): void
    {
        foreach ($modelsToDelete as $model)
        {
            if ($model->is_default == 1)
            {
                throw new Exception("You cannot delete the main department.");
            }
        }

        parent::doSomeActionsForCollectionBeforeDelete($modelsToDelete); // TODO: Change the autogenerated stub
    }
}
