<?php

namespace PixelApp\Services\UserCompanyAccountServices\Signature;

use AuthorizationManagement\PolicyManagement\Policies\BasePolicy;
use CRUDServices\CRUDServiceTypes\DeletingServices\DeletingService;
use PixelApp\Models\UsersModule\Signature;

class SignatureDeletingService extends DeletingService
{

    protected function getModelDeletingSuccessMessage(): string
    {
        return "The Product Has Been Signature Successfully !";
    }

    protected function getModelDeletingFailingErrorMessage(): string
    {
        return "The Signature Failed to Delete !"; // TODO: Change the autogenerated stub
    }

    protected function AuthorizeByPolicy() : bool
    {
        return BasePolicy::check("delete" , Signature::class);
    }


}
