<?php

namespace PixelApp\Services\UserCompanyAccountServices\Signature; 

use CRUDServices\CRUDServiceTypes\DeletingServices\DeletingService;

class SignatureDeletingService extends DeletingService
{

    protected function getModelDeletingSuccessMessage(): string
    {
        return "The Product Has Been Signature Successfully !";
    }

    protected function getModelDeletingFailingErrorMessage(): string
    {
        return "The Signature Failed to Delete !"; // TODO: Change the autogenerated stub
    }
}
