<?php

namespace PixelApp\CustomLibs\PixelCycleManagers\PixelAppsConnectionManagement\PixelAppRouteIdentifiers;

use PixelApp\CustomLibs\PixelCycleManagers\PixelAppsConnectionManagement\PixelAppRouteIdentifiers\Interfaces\DataSendingRouteIdentifier;
use PixelApp\CustomLibs\PixelCycleManagers\PixelAppsConnectionManagement\PixelAppRouteIdentifiers\Traits\DataSendingRouteIdentifierMethods;

class PixelAppPutRouteIdentifier extends PixelAppRouteIdentifier implements DataSendingRouteIdentifier
{
   use DataSendingRouteIdentifierMethods;
}