<?php

namespace PixelApp\Services\SystemConfigurationServices\DropdownLists\BranchesOperations;

use AuthorizationManagement\PolicyManagement\Policies\BasePolicy;
use Exception;
use PixelApp\Models\PixelModelManager;
use PixelApp\Models\SystemConfigurationModels\Branch;
use PixelApp\Services\CoreServices\BulkDestroyService;

class BranchDeletingService extends BulkDestroyService
{

     protected function getModelDeletingFailingErrorMessage(): string
    {
        return 'Failed to delete the record.';
    }
    protected function getModelDeletingSuccessMessage(): string
    {
        return "The record has been deleted successfully.";
    }
    protected function AuthorizeByPolicy(): bool
    {
        return BasePolicy::check('delete', $this->getModelClass());
    }

    protected function getModelClass(): string
    {
        return PixelModelManager::getModelForModelBaseType( Branch::class ); 
    }

    function doSomeActionsForCollectionBeforeDelete($modelsToDelete): void
    {
        foreach ($modelsToDelete as $model)
        {
            if ($model->id == 1) {
                throw new Exception("Deleting Main Branch is not allowed. At least one branch must exist.");
            }

            if ($model->users()->activeUsers()->count() > 0) {
                throw new Exception("Branch can not be deleted as it has active users assigned to it");
            }
        }
        parent::doSomeActionsForCollectionBeforeDelete($modelsToDelete); // TODO: Change the autogenerated stub
    }
}
