<?php

namespace PixelApp\Database\Migrations\MigrationFileStubIdentifierFactories\CompanyMigrationStubFactories;

use PixelApp\Database\Migrations\MigrationFileStubIdentifierFactories\MigrationFileStubIdentifierFactory;

abstract class CompanyMigrationStubIdentifierFactory extends MigrationFileStubIdentifierFactory
{

}